language: php
php:
  - 7.2
  - 7.3
before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev
 - composer dump-autoload
script:
 - ./vendor/bin/phpunit
notifications:
  slack:
    rooms:
      - secure: jhk7/SsA7PrhS0nPzo695buSAUkZrBqGIwYJTpKUioPG34sBcUICNj6hbaJdvpgvNTRaH5HNHmLB7fkC/BphbIey8SLiQgUzECmJRAMbzU2nqpmZxPNHD3Qdu/hEMS0vucaVlWsyhTcRotc91Tt4sSnXEl0HdXGxdsNo8vZZl8sInrs5Sv86PpYNmpyFJm2Hnk1J3qZVlm3J01B3M+J2wBRXfEwlIVvYW7BbbEvUhqiWNtc4/uPrKQKVvk3U00zRdSrWUAYFJWkvLGh4u/yfCuoenI/CNMFiuGjonQ+YYyi4azsGBWY9FpXJNmdW3PZbItgKd+zyVPgySc4jPcOQ3h9mvfcR4b1A+O2DEnsUyKdFsizD9iYv3QGK6YaiJPxBn+ymIykbJkTygGjj4JpLxcuZJpjTyQJilD/NxFfOAjhpPUBYnVa08c7WaejewHbuAn1SedpORLMDsmWHhvFqNCGmIIlT9YWXn6cXVjRJz6aXQFYITBhuu4WTEOFawMhlUYVmTzyAnZtw027fG6arUCvfLc8PC9uBt1avNh+rV+sdcuxwbqX1uj4hz5kMIt+f5Nbrl9IVSIYvMxYNLGC8Y/JyDVWlSOMPErNfoXpfm9KPV55YwuhSZKz2XiijMxGHZpv25Y0u1pqKPTvZNb/fmroHvuQv+J4rdTzEQ6I3sgk=
    on_success: change
    on_failure: change
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
